/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_pak_Main */

#ifndef _Included_test_pak_Main
#define _Included_test_pak_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_pak_Main
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_test_pak_Main_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
